// <auto-generated />
namespace Velvel.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class baseedited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(baseedited));
        
        string IMigrationMetadata.Id
        {
            get { return "201512280601539_base-edited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
