//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonHebrew {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonHebrew() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CommonHebrew", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוספה.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטול.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאור השינוי.
        /// </summary>
        internal static string ChangeDescription {
            get {
                return ResourceManager.GetString("ChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דף שינוי.
        /// </summary>
        internal static string ChangePage {
            get {
                return ResourceManager.GetString("ChangePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קובץ.
        /// </summary>
        internal static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוספת לקוח.
        /// </summary>
        internal static string CreateCustomer {
            get {
                return ResourceManager.GetString("CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוספת מנהל.
        /// </summary>
        internal static string CreateManager {
            get {
                return ResourceManager.GetString("CreateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוספת פרויקט.
        /// </summary>
        internal static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לקוח.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לקוחות.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דף ליקוי.
        /// </summary>
        internal static string DefectPage {
            get {
                return ResourceManager.GetString("DefectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הורדה.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עריכת לקוח.
        /// </summary>
        internal static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עריכת מנהל.
        /// </summary>
        internal static string EditManager {
            get {
                return ResourceManager.GetString("EditManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עריכת פרויקט.
        /// </summary>
        internal static string EditProject {
            get {
                return ResourceManager.GetString("EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דואר אלקטרוני.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כניסה.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יציאה.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם קובץ.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבצים.
        /// </summary>
        internal static string FilesOverview {
            get {
                return ResourceManager.GetString("FilesOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם פרטי.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאור הריצוף.
        /// </summary>
        internal static string FlooringDescription {
            get {
                return ResourceManager.GetString("FlooringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דף ריצוף.
        /// </summary>
        internal static string FlooringPage {
            get {
                return ResourceManager.GetString("FlooringPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלום.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בית.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משפחה.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יציאה.
        /// </summary>
        internal static string LoggOff {
            get {
                return ResourceManager.GetString("LoggOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כניסת משתמש.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנהל.
        /// </summary>
        internal static string ManagerName {
            get {
                return ResourceManager.GetString("ManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנהלים.
        /// </summary>
        internal static string Managers {
            get {
                return ResourceManager.GetString("Managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא קיימים פרויקטים בחשבון זה.
        /// </summary>
        internal static string NoProjectFound {
            get {
                return ResourceManager.GetString("NoProjectFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סקירה.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיסמה.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אימות סיסמה.
        /// </summary>
        internal static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תכניות.
        /// </summary>
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דף אינסטלציה.
        /// </summary>
        internal static string PlumbingPage {
            get {
                return ResourceManager.GetString("PlumbingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרויקט.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרויקטים.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דו&quot;ח.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמירה.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מסמכים חתומים.
        /// </summary>
        internal static string SignedDocuments {
            get {
                return ResourceManager.GetString("SignedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אביזר.
        /// </summary>
        internal static string TableAccessory {
            get {
                return ResourceManager.GetString("TableAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אושר.
        /// </summary>
        internal static string TableApproved {
            get {
                return ResourceManager.GetString("TableApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת שינויים.
        /// </summary>
        internal static string TableChangesTitle {
            get {
                return ResourceManager.GetString("TableChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך.
        /// </summary>
        internal static string TableDate {
            get {
                return ResourceManager.GetString("TableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת ליקויים.
        /// </summary>
        internal static string TableDefectTitle {
            get {
                return ResourceManager.GetString("TableDefectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאור.
        /// </summary>
        internal static string TableDescription {
            get {
                return ResourceManager.GetString("TableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת ריצוף.
        /// </summary>
        internal static string TableFlooringTitle {
            get {
                return ResourceManager.GetString("TableFlooringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רובה.
        /// </summary>
        internal static string TableGrout {
            get {
                return ResourceManager.GetString("TableGrout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מידה.
        /// </summary>
        internal static string TableMeasurement {
            get {
                return ResourceManager.GetString("TableMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מודל.
        /// </summary>
        internal static string TableModel {
            get {
                return ResourceManager.GetString("TableModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת אינסטלציה.
        /// </summary>
        internal static string TablePlumbingTitle {
            get {
                return ResourceManager.GetString("TablePlumbingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר.
        /// </summary>
        internal static string TablePrice {
            get {
                return ResourceManager.GetString("TablePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחיר ליחידה.
        /// </summary>
        internal static string TablePricePerUnit {
            get {
                return ResourceManager.GetString("TablePricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחידות.
        /// </summary>
        internal static string TableQuantities {
            get {
                return ResourceManager.GetString("TableQuantities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חדר.
        /// </summary>
        internal static string TableRoom {
            get {
                return ResourceManager.GetString("TableRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטטוס.
        /// </summary>
        internal static string TableState {
            get {
                return ResourceManager.GetString("TableState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחידת מדידה.
        /// </summary>
        internal static string TableUnitType {
            get {
                return ResourceManager.GetString("TableUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ מחיר.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העלאה.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צפיה.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
